MyBudgetManager/MyBudgetControllerDashboard/MyBudgetControllerDashboard/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('incomeApp.urls')),
    # url(r'', include('costApp.urls')),
]

MyBudgetManager/MyBudgetControllerDashboard/costApp/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'costs$', views.costs_list, name='costs_list'),
    url(r'^cost/(?P<pk>[0-9]+)/$',
        views.cost_detail, name='cost_detail'),
    url(r'^cost/new/$', views.cost_new, name='cost_new'),
    url(r'^cost/(?P<pk>[0-9]+)/edit/$',
        views.cost_edit, name='cost_edit'),
]

MyBudgetManager/MyBudgetControllerDashboard/incomeApp/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # url(r'', views.base_view, name='income_base_view'),
    url(r'^incomes$', views.incomes_list, name='incomes_list'),
    url(r'^income/(?P<pk>[0-9]+)/$',
        views.income_detail, name='income_detail'),
    url(r'^income/new/$', views.income_new, name='income_new'),
    url(r'^income/(?P<pk>[0-9]+)/edit/$',
        views.income_edit, name='income_edit'),
]

MyBudgetManager/MyBudgetControllerDashboard/incomeApp/models.py
from django.db import models
from django.db.models import Q, F, Max, Count, Value, Case, When, Sum, ExpressionWrapper, Avg
from django.utils import timezone
from operator import and_, or_, add
from functools import reduce
from django.contrib.auth.models import User, Group
from django.db.models.functions import Concat
from . import validators

from datetime import datetime, timedelta, MAXYEAR
import re
import collections
from money import Money


class IncomeQuerySet(models.QuerySet):
    def all_incomes(self):
        return self.order_by('id')

    def get_the_income_by_id(self, income_id):
        return self.get(income_id=id)

    def create_filters_from_timestamp(self, timestamp):
        dt = datetime.now()
        filters = {}

        try:
            if re.fullmatch(R"([t](oday)?)", timestamp, re.IGNORECASE):
                filters["dateOfPayment__date"] = datetime.today()
            elif re.fullmatch(R"([t](oday)?)\s*-\s*(\d+)", timestamp, re.IGNORECASE):
                days = re.search(R"([t](oday)?)\s*-\s*(\d+)",
                                 timestamp, re.IGNORECASE).group(3)
                end = datetime.today()
                start = end - timedelta(days=int(days))
                filters["dateOfPayment__range"] = (start, end)
            elif re.fullmatch(R"\d{4}[.][01]?\d[.][0-3]?\d\s*-\s*\d{4}[.][01]?\d[.][0-3]?\d", timestamp):
                dtstring = timestamp.split("-")
                start = datetime.strptime(dtstring[0].strip(), "%Y.%m.%d")
                end = datetime.strptime(dtstring[1].strip(), "%Y.%m.%d")
                filters["dateOfPayment__range"] = (start, end)
            elif re.fullmatch(R"\d{4}-[01]?\d-[0-3]?\d\s*-\s*\d{4}-[01]?\d-[0-3]?\d", timestamp):
                dtstring = timestamp.split("-")
                start = datetime.strptime(
                    "".join([x for x in dtstring[0:3]]).strip(), "%Y%m%d")
                end = datetime.strptime(
                    "".join([x for x in dtstring[3:6]]).strip(), "%Y%m%d")
                filters["dateOfPayment__range"] = (start, end)
            elif re.fullmatch(R"\d{4}[.][01]?\d[.][0-3]?\d [0-2]\d:[0-5]\d:[0-5]\d(?:\.\d+)?Z?\s*-\s*\d{4}[.][01]?\d[.][0-3]?\d [0-2]\d:[0-5]\d:[0-5]\d(?:\.\d+)?Z?", timestamp):
                dtstring = timestamp.split("-")
                start = datetime.strptime(
                    dtstring[0].strip(), "%Y.%m.%d %H:%M:%S")
                end = datetime.strptime(
                    dtstring[1].strip(), "%Y.%m.%d %H:%M:%S")
                filters["dateOfPayment__range"] = (start, end)
            elif re.fullmatch(R"\d{4}[.][01]?\d[.][0-3]?\d [0-2]\d:[0-5]\d\s*-\s*\d{4}[.][01]?\d[.][0-3]?\d [0-2]\d:[0-5]\d", timestamp):
                dtstring = timestamp.split("-")
                start = datetime.strptime(
                    dtstring[0].strip(), "%Y.%m.%d %H:%M")
                end = datetime.strptime(dtstring[1].strip(), "%Y.%m.%d %H:%M")
                filters["dateOfPayment__range"] = (start, end)
            elif re.fullmatch(R"[01]?\d[.][0-3]?\d\s*-\s*[01]?\d[.][0-3]?\d", timestamp):
                dtstring = timestamp.split("-")
                start = datetime.strptime(
                    str(dt.year) + "." + dtstring[0].strip(), "%Y.%m.%d")
                end = datetime.strptime(
                    str(dt.year) + "." + dtstring[1].strip(), "%Y.%m.%d")
                filters["dateOfPayment__range"] = (start, end)
            elif re.fullmatch(R"[0-3]?\d\s*-\s*[0-3]?\d", timestamp):
                dtstring = timestamp.split("-")
                start = datetime.strptime(
                    str(dt.year) + "." + str(dt.month) + "." + dtstring[0].strip(), "%Y.%m.%d")
                end = datetime.strptime(
                    str(dt.year) + "." + str(dt.month) + "." + dtstring[1].strip(), "%Y.%m.%d")
                filters["dateOfPayment__range"] = (start, end)
            elif re.fullmatch(R"\d{4}[.-][01]?\d[.-][0-3]?\d [0-2]\d:[0-5]\d:[0-5]\d(?:\.\d+)?Z?", timestamp):
                if "." in timestamp:
                    dt = datetime.strptime(timestamp, "%Y.%m.%d %H:%M:%S")
                if "-" in timestamp:
                    dt = datetime.strptime(timestamp, "%Y-%m-%d %H:%M:%S")
                filters["dateOfPayment__year"] = dt.year
                filters["dateOfPayment__month"] = dt.month
                filters["dateOfPayment__day"] = dt.day
                filters["dateOfPayment__hour"] = dt.hour
                filters["dateOfPayment__minute"] = dt.minute
                filters["dateOfPayment__second"] = dt.second
            elif re.fullmatch(R"\d{4}[.-][01]?\d[.-][0-3]?\d [0-2]\d:[0-5]\d", timestamp):
                if "." in timestamp:
                    dt = datetime.strptime(timestamp, "%Y.%m.%d %H:%M")
                if "-" in timestamp:
                    dt = datetime.strptime(timestamp, "%Y-%m-%d %H:%M")
                filters["dateOfPayment__year"] = dt.year
                filters["dateOfPayment__month"] = dt.month
                filters["dateOfPayment__day"] = dt.day
                filters["dateOfPayment__hour"] = dt.hour
                filters["dateOfPayment__minute"] = dt.minute
            elif re.fullmatch(R"\d{4}[.-][01]?\d[.-][0-3]?\d", timestamp):
                if "." in timestamp:
                    dt = datetime.strptime(timestamp, "%Y.%m.%d")
                if "-" in timestamp:
                    dt = datetime.strptime(timestamp, "%Y-%m-%d")
                filters["dateOfPayment__year"] = dt.year
                filters["dateOfPayment__month"] = dt.month
                filters["dateOfPayment__day"] = dt.day
            elif re.fullmatch(R"[01]?\d[.-][0-3]?\d", timestamp):
                if "." in timestamp:
                    dt = datetime.strptime(timestamp, "%m.%d")
                if "-" in timestamp:
                    dt = datetime.strptime(timestamp, "%m-%d")
                filters["dateOfPayment__month"] = dt.month
                filters["dateOfPayment__day"] = dt.day
            elif re.fullmatch(R"[0-2]\d:[0-5]\d:[0-5]\d(?:\.\d+)?Z?", timestamp):
                dt = datetime.strptime(timestamp, "%H:%M:%S")
                filters["dateOfPayment__hour"] = dt.hour
                filters["dateOfPayment__minute"] = dt.minute
                filters["dateOfPayment__second"] = dt.second
            elif re.fullmatch(R"[0-2]\d:[0-5]\d", timestamp):
                dt = datetime.strptime(timestamp, "%H:%M")
                filters["dateOfPayment__hour"] = dt.hour
                filters["dateOfPayment__minute"] = dt.minute
            elif re.fullmatch(R"[0-3]?\d", timestamp):
                dt = datetime.strptime(timestamp, "%d")
                filters["dateOfPayment__day"] = dt.day
            else:
                filters["dateOfPayment__year"] = MAXYEAR
        except ValueError:
            filters["dateOfPayment__year"] = MAXYEAR

        return filters
    
    def filter_by_timestamp(self, timestamp):
        filters = self.create_filters_from_timestamp(timestamp)
        return self.filter(**filters)
    
    def filter_by_description(self, description):
        filters = description.split(",")
        filters = [f.strip() for f in filters if "" is not f.strip()]
        if not filters:
            filters = [""]
        return self.filter(
            reduce(or_, [Q(description__icontains=description) for description in filters]))
    
    def filter_by_category(self, category):
        filters = category.split(",")
        filters = [f.strip() for f in filters if "" is not f.strip()]
        if not filters:
            filters = [""]
        return self.filter(
            reduce(or_, [Q(category__icontains=category) for category in filters]))


class Incomes(models.Model):
    id = models.AutoField(db_column='id', primary_key=True,
                          null=False, unique=True)
    registrationDate = models.DateTimeField(
        db_column='registrationDate', blank=False, null=False, verbose_name="Registration Date", help_text="e.g. Sept. 12, 2019")
    dateOfPayment = models.DateTimeField(
        db_column='dateOfPayment', blank=False, null=False, verbose_name="Date Of Payment", help_text="e.g. Sept. 12, 2019")
    amount = models.IntegerField(
        db_column='amount', blank=False, null=False, verbose_name="Amount", help_text="e.g. 578 HUF")
    description = models.TextField(db_column='description', blank=False, null=False,
                                   verbose_name="Description", help_text="e.g. Bejovo giro jovairas SP...")
    category = models.CharField(db_column='category', max_length=50, blank=False, null=False,
                                verbose_name="Category", help_text="e.g. Interest Income and Other Revenue From Bank")
    # objects = TestCaseQuerySet.as_manager()

    class Meta:
        managed = False
        db_table = 'incomes'

    def __str__(self):
        return str(self.name)

MyBudgetManager/MyBudgetControllerDashboard/incomeApp/forms.py
from django import forms

from .models import Incomes


class IncomeForm(forms.ModelForm):

    class Meta:
        model = Incomes
        fields = ('registrationDate', 'dateOfPayment',
                  'amount', 'description', 'category',)
        widgets = {
            'registrationDate': forms.Textarea(attrs={'cols': 20, 'rows': 20}),
            'dateOfPayment': forms.Textarea(attrs={'cols': 20, 'rows': 20}),
            'amount': forms.Textarea(attrs={'cols': 20, 'rows': 20}),
            'description': forms.Textarea(attrs={'cols': 20, 'rows': 20}),
            'category': forms.Textarea(attrs={'cols': 20, 'rows': 20})
        }


class IncomesFormFilter(forms.Form):
    id = forms.CharField(required=False)
    registrationDate = forms.CharField(required=False)
    dateOfPayment = forms.CharField(required=False)
    amount = forms.CharField(required=False)
    description = forms.CharField(required=False)
    category = forms.CharField(required=False)

MyBudgetManager/MyBudgetControllerDashboard/incomeApp/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from .models import Incomes
from .forms import IncomeForm


# def base_view(request):
#     return render(request, 'incomeApp/income_base_view.html', {})
#     # return render(request, 'incomeApp/incomes_list.html', {})

def incomes_list(request):
    incomes = Incomes.objects.all()
    return render(request, 'incomeApp/incomes_list.html', {'incomes': incomes})


def income_detail(request, pk):
    income = get_object_or_404(Incomes, pk=pk)
    return render(request, 'incomeApp/income_detail.html', {'income': income})


def income_new(request):
    if request.method == "POST":
        form = IncomeForm(request.POST)
        if form.is_valid():
            income = form.save(commit=False)
            income.save()
            return redirect('income_detail', pk=income.pk)
    else:
        form = IncomeForm()
    return render(request, 'incomeApp/income_edit.html', {'form': form})


def income_edit(request, pk):
    income = get_object_or_404(Incomes, pk=pk)
    if request.method == "POST":
        form = IncomeForm(request.POST, instance=income)
        if form.is_valid():
            income = form.save(commit=False)
            income.save()
            return redirect('income_detail', pk=income.pk)
    else:
        form = IncomeForm(instance=income)
    return render(request, 'incomeApp/income_edit.html', {'form': form})


# def incomes(request):
#     form = IncomesFormFilter(request.GET)
#     incomes_list = Incomes.objects.allfilters(CreateFilters(form))

#     return render(request, 'incomeApp/incomes_list.html', {'incomes_list': incomes_list})


# def testresults(request):
#     form = IncomesFormFilter(request.GET)

#     resultlist = Incomes.objects.allfilters(CreateFilters(form))

#     page = request.GET.get('page', 1)

#     paginator = Paginator(resultlist, 25)
#     try:
#         myresults = paginator.page(page)
#     except PageNotAnInteger:
#         myresults = paginator.page(1)
#     except EmptyPage:
#         myresults = paginator.page(paginator.num_pages)

#     PassFailRatiodict = PassFailRatio(resultlist)
#     TestedProductsdict = TestedProducts(resultlist)
#     FailureCausesdict = FailureCauses(resultlist)
#     resultdict = TestResultsbyFWVersion(resultlist)

#     data = {
#         'resultlist': myresults,
#         'filters': CreateFilters(form),
#         'testresultsnumber': TotalTestResultCount(resultlist),
#         'averageduration': AverageDuration(resultlist),
#         'passedfailedratiodata': json.dumps(list(PassFailRatiodict.values())),
#         'passedfailedratiolabel': json.dumps(list(PassFailRatiodict.keys())),
#         'testedproductsdata': json.dumps(list(TestedProductsdict.values())),
#         'testedproductslabel': json.dumps(list(TestedProductsdict.keys())),
#         'failureclassesdata': json.dumps(list(FailureCausesdict.values())),
#         'failureclasseslabel': json.dumps(list(FailureCausesdict.keys())),
#         'resultsbytestedfirmwaresdata': json.dumps(list(TestResultsbyFWVersionData(resultdict))),
#         'resultsbytestedfirmwareslabel': json.dumps(list(TestResultsbyFWVersionLabel(resultdict)))
#     }
#     return render(request, 'DashboardApp/testresults.html', {'data': data})

MyBudgetManager/MyBudgetControllerDashboard/incomeApp/templates/incomeApp/income_base_view.html
{% extends 'incomeApp/base.html' %} 
{% block content %}  
    {% comment %} <div class="income"> {% endcomment %}
      {% comment %} <span> EDIT HERE: <a class="btn btn-default" href="{% url 'income_edit' pk=income.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></span> {% endcomment %}
      {% comment %} <a class="btn btn-default" href="{% url 'income_edit' pk=income.pk %}">
        <span class="glyphicon glyphicon-pencil">Edit</span>
      </a> {% endcomment %}
      {% comment %} <h1>{{ income.description }}</h1>
      <p>Registration date: {{ income.registrationDate }}</p>
      <p>Date of payment: {{ income.dateOfPayment }}</p>
      <p>Amount: {{ income.amount }}</p>
      <p>Description: {{ income.description }}</p>
      <p>Category: {{ income.category }}</p>
    </div> {% endcomment %}

    <div>
        {% comment %} <img src="{% static 'images/Summary_logo.png' %}" width="30" height="30" alt=""> {% endcomment %}
        <h1>This is heading 1</h1>
    </div>



{% endblock %}

MyBudgetManager/MyBudgetControllerDashboard/incomeApp/templates/incomeApp/income_detail.html
{% extends 'incomeApp/base.html' %} 
{% block content %}  
    {% comment %} <div class="income"> {% endcomment %}
      {% comment %} <span> EDIT HERE: <a class="btn btn-default" href="{% url 'income_edit' pk=income.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></span> {% endcomment %}
      {% comment %} <a class="btn btn-default" href="{% url 'income_edit' pk=income.pk %}">
        <span class="glyphicon glyphicon-pencil">Edit</span>
      </a> {% endcomment %}
      {% comment %} <h1>{{ income.description }}</h1>
      <p>Registration date: {{ income.registrationDate }}</p>
      <p>Date of payment: {{ income.dateOfPayment }}</p>
      <p>Amount: {{ income.amount }}</p>
      <p>Description: {{ income.description }}</p>
      <p>Category: {{ income.category }}</p>
    </div> {% endcomment %}

    <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">INCOME DETAILS</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>ID</th>
                <th>REGISTRATION DATE</th>
                <th>DATE OF PAYMENT</th>
                <th>AMOUNT</th>
                <th>DESCRIPTION</th>
                <th>CATEGORY</th>
            </tr>
            </thead>
            <tbody>
             
            <tr>
                <td width="5%">{{ income.id }}</td>
                <td width="15%">{{ income.registrationDate.date }}</td>
                <td width="15%">{{ income.dateOfPayment.date }}</td>
                <td width="15%" align="right">{{ income.amount }} HUF</td>
                <td width="30%" align="left"> <font size="2">{{ income.description }}</font></td>
                <td width="20%">{{ income.category }}</td>
            </tr>

            </tbody>                  
        </table>
        </div>
        <a class="btn btn-primary" href="{% url 'income_edit' pk=income.pk %}">
            <span class="icon text-white-50">
                <i class="fas fa-arrow-right"></i>
            </span>
            <span class="text">EDIT</span>           
            {% comment %} <span class="glyphicon glyphicon-pencil">Edit</span> {% endcomment %}
        </a>
        {% comment %} <p> TESZT : 
            <i class="fab fa-affiliatetheme"></i>
        </p> {% endcomment %}
    </div>
    </div>



{% endblock %}

MyBudgetManager/MyBudgetControllerDashboard/incomeApp/templates/incomeApp/income_edit.html
{% extends 'incomeApp/base.html' %}

{% block content %}
    <h1>Edit Income Element</h1>
    {% comment %} <form method="POST" action="{{ income_edit }}" class="form-horizontal">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form> {% endcomment %}

    <form class="form-horizontal" method="POST" action="{{ income_edit }}" style="width: 200%" >
        {% csrf_token %}
        <div class="card">
            {% comment %} <div class="card-header">
                <strong>Edit Income Element</strong>
            </div> {% endcomment %}
            <div class="card-body">
                {% for field in form.visible_fields %}
                <b>{{ field.label }}</b>
                {% comment %} <input class="form-control is-invalid income_property_theme" id="{{ field.html_name }}"
                                                    type="{{ field.field.widget.input_type }}"
                                                    placeholder="{{ field.help_text }}" name="{{ field.html_name }}"
                                                    value="{{ field.value|default:"" }}"> {% endcomment %}
                {% if field.label == "Description" %}
                <textarea 
                        class="form-control is-invalid description_income_edit income_property_theme"                        
                        id="{{ field.html_name }}"                        
                        name="{{ field.html_name }}"
                        style="height: 240px"
                        value="">{{ field.value|default:"" }} </textarea>
                {% else %}
                <input class="form-control is-invalid income_property_theme" id="{{ field.html_name }}"
                                                    type="{{ field.field.widget.input_type }}"
                                                    placeholder="{{ field.help_text }}" name="{{ field.html_name }}"
                                                    value="{{ field.value|default:"" }}">
                {% comment %} <textarea 
                        class="form-control is-invalid income_property_theme"                        
                        id="{{ field.html_name }}"                        
                        name="{{ field.html_name }}"
                        value="">{{ field.value|default:"" }} </textarea> {% endcomment %}
                {% endif %}

                {% endfor %}

                {% comment %} {{ form.as_p }} {% endcomment %}
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>


    {% comment %} <form method="POST" action="{{ income_edit }}" class="list-group">{% csrf_token %}
        <ul>
            <li><label for="{{ field.registrationDate.id_for_label }}">Registration Date:</label> <input id="{{ field.registrationDate.id_for_label }}" name="{{ field.registrationDate.id_for_label }}" type="{{ field.field.widget.input_type }}" value="{{ field.registrationDate.id_for_label }}" /></li>
            <li><label for="id_dateOfPayment">Date Of Payment:</label> <input id="id_dateOfPayment" name="dateOfPayment" type="text" value="2019-02-04 01:00:00" /></li>
            <li><label for="id_amount">Amount:</label> <input id="id_amount" name="amount" type="number" value="578" /></li>
            <li><label for="id_description">Description:</label> <textarea id="id_description" cols="40" name="description" rows="10">JOVAIRAS SNKFHH8005551597
                    HS-Szamlavezetesi dijkedvezmeny
                    ONLHSFHH8LAKSAG H032
                    Erteknap: 2019.02.04</textarea> <span class="helptext">Short description about income item</span></li>
            <li><label for="id_category">Category:</label> <input id="id_category" maxlength="35" name="category" type="text" value="Interest Income and Other Revenue From Bank" /></li>
        </ul>
        <p><button class="btn btn-primary" type="submit">Save</button></p>



    </form>

    <h1>TEST</h1>

    <p>Registration date: {{ income.registrationDate }}</p>

            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>ID</th>
                <th>REGISTRATION DATE</th>
                <th>DATE OF PAYMENT</th>
                <th>AMOUNT</th>
                <th>DESCRIPTION</th>
                <th>CATEGORY</th>
            </tr>
            </thead>
            <tbody>
             
            <tr>
                <td width="5%">{{ income.id }}</td>
                <td width="15%">{{ income.registrationDate.date }}</td>
                <td width="15%">{{ income.dateOfPayment.date }}</td>
                <td width="15%" align="right">{{ income.amount }} HUF</td>
                <td width="30%" align="left"> <font size="2">{{ income.description }}</font></td>
                <td width="20%">{{ income.category }}</td>
            </tr>

            </tbody>                  
        </table> {% endcomment %}
{% endblock %}
    

MyBudgetManager/MyBudgetControllerDashboard/incomeApp/templates/incomeApp/incomes_list.html
{% extends 'incomeApp/base.html' %}
{% block content %}
{% comment %} {% for income in incomes %}
<div class="income">
  <div class="date">
    {{ income.dateOfPayment }}
  </div>
  <h1><a href="{% url 'income_detail' pk=income.pk %}">{{ income.description }}</a></h1>
  <p>Registration date: {{ income.registrationDate }}</p>
  <p>Date of payment: {{ income.dateOfPayment }}</p>
  <p>Amount: {{ income.amount }}</p>
  <p>Description: {{ income.description }}</p>
  <p>Category: {{ income.category }}</p>
</div>
{% endfor %} {% endcomment %}
{% comment %} <div class="incomes_list">
  <table>
    <tr>
      <th>Registration date</th>
      <th>Date of payment</th>
      <th>Amount</th>
      <th>Description</th>
      <th>Category</th>
    </tr>
    {% for income in incomes %}
    <tr>
      <td>{{ income.registrationDate }}</td>
      <td>{{ income.dateOfPayment }}</td>
      <td>{{ income.amount }}</td>
      <td><a href="{% url 'income_detail' pk=income.pk %}">{{ income.description }}</a></td>
      <td>{{ income.category }}</td>
    </tr>
    {% endfor %}
  </table> {% endcomment %}

  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">INCOMES</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>ID</th>
              <th>REGISTRATION DATE</th>
              <th>DATE OF PAYMENT</th>
              <th>AMOUNT</th>
              <th>DESCRIPTION</th>
              <th>CATEGORY</th>
            </tr>

            <tr>
              <td>
                <input
                  title="Filter examples: &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa"
                  type="text" name="id" placeholder="" value="{{ data.filters.id|default:"" }}" class="form-control" />
              </td>
              <td>
                <input
                  title="Filter examples: &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa"
                  type="text" name="registrationDate" placeholder=""
                  value="{{ data.filters.registrationDate|default:"" }}" class="form-control" />
              </td>
              <td>
                <input
                  title="Filter examples: &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa"
                  type="text" name="dateOfPayment" placeholder="" value="{{ data.filters.dateOfPayment|default:"" }}"
                  class="form-control" />
              </td>
              <td>
                <input
                  title="Filter examples: &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa"
                  type="text" name="amount" placeholder="" value="{{ data.filters.amount|default:"" }}"
                  class="form-control" />
              </td>
              <td>
                <input
                  title="Filter examples: &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa"
                  type="text" name="description" placeholder="" value="{{ data.filters.description|default:"" }}"
                  class="form-control" />
              </td>
              <td>
                <input
                  title="Filter examples: &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa &#10;   blaaaaa"
                  type="text" name="category" placeholder="" value="{{ data.filters.category|default:"" }}"
                  class="form-control" />
              </td>
            </tr>
          </thead>
          <tbody>
            {% for income in incomes %}
            <tr>
              <td width="5%">{{ income.id }}</td>
              <td width="15%">{{ income.registrationDate.date }}</td>
              <td width="15%">{{ income.dateOfPayment.date }}</td>
              <td width="15%" align="right">{{ income.amount }} HUF</td>
              <td width="30%" align="left">
                <font size="2"><a href="{% url 'income_detail' pk=income.pk %}">{{ income.description }}</a></font>
              </td>
              <td width="20%">{{ income.category }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  {% comment %} <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">REGISTRATION DATE</th>
        <th scope="col">DATE OF PAYMENT</th>
        <th scope="col">AMOUNT</th>
        <th scope="col">DESCRIPTION</th>
        <th scope="col">CATEGORY</th>
      </tr>
    </thead>
    <tbody>
      {% for income in incomes %}
      <tr>
        <td width="5%">{{ income.id }}</td>
        <td width="15%">{{ income.registrationDate }}</td>
        <td width="15%">{{ income.dateOfPayment }}</td>
        <td width="10%">{{ income.amount }}</td>
        <td width="35%"><a href="{% url 'income_detail' pk=income.pk %}">{{ income.description }}</a></td>
        <td width="20%">{{ income.category }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table> {% endcomment %}

  {% endblock %}